spring:
  application:
    name: mailService
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: '127.0.0.1'
    port: 5672
    username: 'thalys'
    password: '123456'