eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: eureka-server
server:
  port: 8761
