spring:
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: identityService
  datasource:
    password: '123456'
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/micro
springdoc:
  swagger-ui:
    enabled: 'true'
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
server:
  port: '8081'
