server:
  port: 8080
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-identity
          uri:
            http://localhost:8081
          predicates:
            - Path=/api/v1/identity/**