eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: service-identity
server:
  port: 8081
management:
  tracing:
    sampling:
      probability: '1.0'