spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  application:
    name: config-server
  profiles:
    active: native
server:
  port: 8888
