package com.identityservice.application.response.register

import com.identityservice.application.enums.RegistrationEnum

class RegistrationSuccessResponse: RegistrationResponse(RegistrationEnum.SUCCESS)